### ISSUE TITLE
Add UserData support for EKS

### ISSUE THREAD

**Issue by SimplySeth** [keikoproj/instance-manager#104]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request

**What happened**:

Can't find where to place the UserData to inject into the Autoscale Group through Cloudformation.

**What you expected to happen**:

Be able to inject UserData to CloudFormation

- Kubernetes version:

1.15 , 1.16
```

**Comment by eytan-avisror** [comment]
Hey @SimplySeth 
The cloudformation provisioner has been deprecated with instance-manager v0.6.0, the new eks provisioner now provisions resources directly on AWS.

An example spec is available here:
https://github.com/keikoproj/instance-manager#eks-sample-spec-alpha-2

Bootstrap arguments can be provided through the CR `.spec.eks.configuration.bootstrapArguments`, you can provide taints and labels directly on the CR config as well without needing to pass them on a string via bootstrap arguments.

**Comment by eytan-avisror** [comment]
Having additional UserData might actually be an interesting use-case - right now we can only control the bootstrap arguments that are passed in to the `bootstrap.sh` script (which then go to kubelet) which comes with standard EKS AMIs.

However, potentially we can introduce a new option here, for example:
```
spec:
  provisioner: eks
  eks:
    configuration:
      userData: |
        #!/bin/bash
        this is where you can add your custom script
```

Would this be useful for your use-case?
if you can provide more information on how you would use this it would be helpful.

**Comment by SimplySeth** [comment]
> Having additional UserData might actually be an interesting use-case - right now we can only control the bootstrap arguments that are passed in to the `bootstrap.sh` script (which then go to kubelet) which comes with standard EKS AMIs.
> 
> However, potentially we can introduce a new option here, for example:
> 
> ```
> spec:
>   provisioner: eks
>   eks:
>     configuration:
>       userData: |
>         #!/bin/bash
>         this is where you can add your custom script
> ```
> 
> Would this be useful for your use-case?
> if you can provide more information on how you would use this it would be helpful.

Yes that would be greatly useful to have `userData:`. Thx

**Comment by vgunapati** [comment]
@eytan-avisror  Will the following be more helpful if we want to run pre and post `bootstrap.sh`

example:
```
spec:
  provisioner: eks
  eks:
    configuration:
      userData: 
        preBootStrap: |
          #!/bin/bash
          this is where you can add your custom script
        postBootStrap: |
           #!/bin/bash
          this is where you can add your custom script

WDYT?
```

**Comment by eytan-avisror** [comment]
@vgunapati 
I was thinking of doing only preBootstrap.. what would be the use-case for postBootstrap? I think generally people want to use this for running some package installations before the instance joins the cluster.
But I agree it's a valid thing to consider and will give more flexibility to users. 

Maybe nicer API would be:
```
spec:
  provisioner: eks
  eks:
    configuration:
      userData: 
      - stage: preBootstrap
        data: |
          #!/bin/bash
          this is where you can add your custom script
      - stage: postBootstrap
        data: |
          #!/bin/bash
          this is where you can add your custom script
```

Also this might be problematic since it ends up in a single script - in this case we have the `#!/bin/bash` twice, this is one of the reason I preferred defaulting to `preBootstrap`.
