### ISSUE TITLE
v1alpha2 API Change Suggestions

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/instance-manager#113]
We should start to think about changes we want to make for v1alpha2.
We should explore adding these as new fields in v1alpha1 so that it's easy to migrate.

#### crdName

this can be either the full crd name or just the resource name, e.g. `rollingupgrades.upgrademgr.keikoproj.io` or `rollingupgrades`, should we just call it `name`?

```yaml
spec:
  strategy:
    provisioner: eks
    crd:
      crdName: rollingupgrades.upgrademgr.keikoproj.io       <- old
---
      name: rollingupgrades.upgrademgr.keikoproj.io          <- new
```

####  statusJSONPath

This accepts a '.' separated path for getting a nested string from the custom resource, and check whether its succeeded or failed using `statusSuccessString` and `statusFailureString`.
We can use something similar to a LabelSelector API

```yaml
spec:
  strategy:
    provisioner: eks
    crd:
      statusJSONPath: .status.currentStatus       <- old
      statusSuccessString: completed
      statusFailureString: error
---
      selector:                                   <- new
      - field: .status.currentStatus
        value: completed
        kind:  Success
      - field: .status.currentStatus
        value: error
        kind:  Failure
```

The full diff can be something like:
```yaml
spec:
  strategy:
    provisioner: eks
    crd:
      name: rollingupgrades.upgrademgr.keikoproj.io
      selector:
      - field: .status.currentStatus
        value: completed
        kind:  Success
      - field: .status.currentStatus
        value: error
        kind:  Failure 
      spec: |
        < .. some custom resource spec .. >
```
This seems much cleaner.

### EKS Configuration

We can accept clusterName as an optional flag now in order to avoid using the clusterName field, we can omit/ignore it in v1alpha2 and make the controller flag mandatory in some later version
```yaml
spec:
  eks:
    configuration:
      clusterName: my-eks-cluster
```

### EKS-Managed Configuration

same can apply for eks-managed `clusterName` as above using a controller flag.
`nodeRole` should possible change to `roleName` and also accept a short version of the role.

```yaml
spec:
  eks-managed:
    configuration:
      nodeRole: arn:aws:iam::012345678910:role/basic-eks-role
---
      roleName: basic-eks-role
```
