### ISSUE TITLE
GitOps: Reconcile ConfigMaps and default values

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/instance-manager#141]
In order to support use-cases around GitOps, we should allow users to define 'boundaries' of configurations into `adminConfig` and `sharedConfig`

### instance-manager ConfigMap
The new configmap will be watched by the controller, and trigger a reconcile on IGs once the configuration has changed. to keep consistency we will add status fields to instance-groups to note down the last reconciled configuration hash, and the current configuration hash.

The configmap will be made up of a few sections, `boundaries` and `defaults`.

#### Boundaries
Boundaries defines the two types of configurations, **admin** configurations and **shared** configurations. the configurations will be specified in a list by the JSON path.

```yaml
data:
  boundaries:
    adminConfig:
    - .spec.eks.configuration.image
    sharedConfig:
    - .spec.eks.configuration.securityGroups
```

#### Defaults
Defaults will define the actual default values to use for both admin and shared config

```yaml
data:
  defaults:
    spec:
      eks:
        configuration:
          image: ami-123456789012
```

##### Boundaries - Admin Config
Admin config items, if referenced, should have a matching default value in the configmap, CR provided values will take a second priority if the default value is missing. for example, if the boundary is configured as follows it would mean that the image will be taken from the configmap even though it may be referenced in the custom resource.

```yaml
data:
  boundaries:
    adminConfig:
    - .spec.eks.configuration.image
  defaults:
    spec:
      eks:
        configuration:
          image: ami-123456789012
```

##### Boundaries - Shared Config
Shared config items, if referenced, should have a matching default value in the configmap, CR provided values will be **MERGED** if possible (e.g. tags, labels, etc.), otherwise the CR provided value will take priority (e.g. strategy). for example, if the boundary is configured as follows it would mean that the tags and security groups will be merged with the CR values if they are provided.

```yaml
data:
  boundaries:
    sharedConfig:
    - .spec.eks.configuration.labels
    - .spec.eks.configuration.securityGroups
  defaults:
    spec:
      eks:
        configuration:
          securityGroups: 
          - sg-04aaa0444a04a0444
          tags:
          - key: some-tag-key
            value: some-tag-value
```

These changes will enable GitOps by allowing the cluster owner to define which configurations need to be managed by the administrator, and which configurations must be referenced in the custom resource.

This will enable users to submit 'shortened' versions of the CR via GitOps tools such as ArgoCD, such as the below example, while the missing configuration values can be provided by the administrator through the configmap.

```yaml
apiVersion: instancemgr.keikoproj.io/v1alpha1
kind: InstanceGroup
metadata:
  name: my-instance-group
  namespace: some-user-namespace
spec:
  provisioner: eks
  eks:
    maxSize: 9
    minSize: 3
    configuration:
      labels:
        my-custom-label: "true"
      instanceType: m5.large
      securityGroups: 
      - sg-04aaa0444a04a0444
      tags:
      - key: some-tag-key
        value: tag-value
```

**Comment by eytan-avisror** [comment]
Consider changing the configmap keys for boundaries to `restricted` & `shared` instead, maybe it's a bit clearer this way.

```
data:
  boundaries:
    restricted:
    - .spec.eks.configuration.image
    shared:
    - .spec.eks.configuration.securityGroups
```
