### ISSUE TITLE
GitOps: Configmap boundary "shared" merge strategy might be too vague

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/instance-manager#149]
Today the following boundaries are allowed:
```
data:
  boundaries:
    restricted:
    - .spec.eks.configuration.image
    shared:
    - .spec.eks.configuration.securityGroups
```

using `shared` might be too generic and vague in terms of what type of merge.
We should consider a more concrete approach to defining the merge strategy of a shared configuration.

For example:

```
data:
  boundaries:
    restricted:
    # stays the same - 1st priority given to default value
    - .spec.eks.configuration.image
    shared:
      merge:
      # merge CR values with default values 
      - .spec.eks.configuration.securityGroups
      replace:
      # replace default values with CR values
      - spec.eks.configuration.taints
```
