### ISSUE TITLE
Support multiple userData stages by name

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/instance-manager#158]
We should change the API while it's unreleased from
```yaml
userData:
  - stage: PreBootstrap
    script: | <content>
```

to
```yaml
  - name: my-stage 
    stage: PreBootstrap
    script: | <content>
```
This will allow multiple scripts to be executed and better ordering
