### ISSUE TITLE
EPIC: support launch templates

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/instance-manager#17]
instance-manager should support launch templates.
This can be done as a separate kind, e.g. `Kind: InstanceGroupTemplate` (or different), and can then reference it in InstanceGroup e.g. `.spec.provisioner.configuration.template`.

**Comment by eytan-avisror** [comment]
Possible approach on extending the existing API to add basic support for launch templates

```
  eks:
    useTemplate: true
    configuration:
      < .. basic configuration .. >
      instanceType: m5.large        # default, sets m5.large to 100%
      mixedInstancesPolicy:         # optional
        spotRatio: 50%             # the ratio of spot/on-demand, if spot enabled, defaults to 100% if not provided
        instanceTypes:              # optional, overrides instanceType if provided
        - type: m5.large
         weight: 50%
        - type: m5.xlarge
         weight: 50%
    status:
      < .. status .. >
      activeLaunchTemplateName: some-template
```

For processing upgrades we can set the launch template version to always be `latest`, this means once we update the launch template, it will already be 'set' on the autoscaling group, and all that's needed is to process the rotation.

To check whether rotation is needed, we can compare the latest template version number with the autoscaling instances' version.

Code should refactor to have a more generic wrapper for configuration, e.g. `CreateConfiguration` instead of `CreateLaunchConfiguration`, which could either call a method to create a launch configuration, or create a launch template, depending on `eks.useTemplate` boolean.

main benefits of doing this are:
- no more limits on number of templates
- deleting templates will only happen on IG delete flow (no need to delete on upgrade due to use of versions)
- using mixed instances & spot ratio

**Comment by shrinandj** [comment]
Instead of `useTemplate: true`, can we add something extensible? Say, `configType: launchTemplates`? The default is basically`configType: launchConfig`. If there are more such options tomorrow, those could be added as additional supported values of the key `configType`.

WDYT?

**Comment by eytan-avisror** [comment]
That's also a possiblity, maybe clarify it further to something like this
```
eks:
    type: LaunchConfiguration
    type: LaunchTemplate
    < .. size .. >
    configuration:
      < .. config .. >
```
but maybe `type` is not clear enough. I think we should avoid shortcuts e.g. `config` but also avoid longer names such as `configurationType` if possible.

**Comment by eytan-avisror** [comment]
We should probably hold on this until cluster-autoscaler supports launch templates, as it currently does not.

**Comment by cspargo** [comment]
@eytan-avisror curious what's missing from cluster-autoscaler? I've been using it with launch-templates for some time.

**Comment by eytan-avisror** [comment]
Hi @cspargo 

Do you use mixed instances in your scaling groups?

I was looking at the below comment:
https://github.com/kubernetes/autoscaler/pull/1473#issuecomment-461396544

But on second look the comment might be a bit old and support may have been added in latest version.
I will double check and see whether we can prioritize this feature.

**Comment by eytan-avisror** [comment]
Looks like cluster-autoscaler DOES support launch templates, however there are some caveats which are described here:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#using-mixed-instances-policies-and-spot-instances

For now we can move forward with this feature

**Comment by shaoxt** [comment]
```
      mixedInstancesPolicy:         # optional
        spotRatio: 50%              # the ratio of spot/on-demand, if spot enabled, defaults to 100% if not provided
        instanceTypes:              # optional, overrides instanceType if provided
        - type: m5.large
         weight: 50%
        - type: m5.xlarge
         weight: 50%
```

1.  default instance type needs a weight too
2. Weight is not percentage...,
    ```
        instanceTypes:              # optional, overrides instanceType if provided
        - type: m5.large
         weight: 2
        - type: m5.xlarge
         weight: 4
    ```
3. The order is matter,
     First one will be taken as default ? then second one, and third one.

For sample family instance types
```
       mixedInstancesPolicy:         # optional
        spotRatio: 50%              # the ratio of spot/on-demand, if spot enabled, defaults to 100% if not provided
        instanceTypes:              # optional, overrides instanceType if provided
        - type: m5.xlarge
         weight: 4
        - type: m5a.xlarge
         weight: 4
```

**Comment by eytan-avisror** [comment]
Thanks @shaoxt did some more reading on these APIs

We will need to add an EC2 client to make the following calls:

- CREATE - [CreateLaunchTemplateInput](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#CreateLaunchTemplateInput)
- UPDATE [CreateLaunchTemplateVersionInput](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#CreateLaunchTemplateVersionInput)
- DELETE [DeleteLaunchTemplateInput](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#DeleteLaunchTemplateInput)

This replaces the launch configuration attached to ASG with a launch template.
This means we need to create/update the scaling group with the launch template instead of a launch config given the custom resource provisioner has a configuration `type: LaunchTemplate`.

As part of the UpdateAutoScalingGroup call, we now need to set the launch template / policy via [MixedInstancesPolicy](https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#MixedInstancesPolicy) type, this will set both the launch template id/version and the instance types/weights.

[MIxedInstancesPolicy.InstancesDistribution](https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#InstancesDistribution) sets the distribution between spot/on-demand

[LaunchTemplateOverrides](https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#LaunchTemplateOverrides) can be used to set the instance types and weights

API can look like:
```
eks:
    type: LaunchTemplate
    minSize: 32  # refers to scaling index of vcpu/mem when using mixedInstancesPolicy
    maxSize: 256
    configuration:
      < .. basic configuration .. >
      instanceType: <instanceType>        # ignored when mixedInstancesPolicy is provided
      mixedInstancesPolicy:         # optional
        spotRatio: 50%              # the ratio of spot/on-demand, if spot enabled, defaults to 100% if not provided
        instanceTypes:              # optional, overrides instanceType if provided
        - type: m5.xlarge
         weight: 4
        - type: m5.2xlarge
         weight: 8

    status:

      < .. status .. >

      activeLaunchTemplateName: some-template
```

This will launch a mix of m5.xlarge and m5.2xlarge to meet the desired weight of minSize (32), while 50% of the capacity will try to launch spot instances.

Still need to play around with the APIs to see if there is something else that needs to be exposed and whether the above is accurate

**Comment by eytan-avisror** [comment]
Some minor changes to the API design.

```yaml
eks:
  type: LaunchTemplate
  minSize: 32  # refers to scaling index of vcpu/mem when using mixedInstancesPolicy
  maxSize: 256
    configuration:
      < .. basic configuration .. >
      instanceType: <instanceType>   # primary instance type
     
      mixedInstancesPolicy:          # optional
        strategy: LowestPrice        # optional, LowestPrice default, valid values (LowestPrice, Capacity)
        spotPools: 2                 # optional, only relevant when strategy is LowestPrice, defines how many instance pools to choose for spot, defaults to 2
        baseCapacity: 3              # optional, the base on-demand capacity, defaults to 0
        spotRatio: 50%               # optional, the ratio of spot/on-demand, on top of base capacity if spot enabled, defaults to 0 if not provided (e.g. all instances are on-demand)

        # if both instancePool and instanceTypes is not specified, GenerationFlexible will be used to determine instances to use

        instancePool: GenerationFlexible  # optional, defaults to GenerationFlexible, valid values are GenerationFlexible or SizeFlexible, if provided there is no need to enumerate the instance types below, it will auto derive which types to use according to primary instance type and pool type.

        instanceTypes:               # optional, allows to specify which instance types and weights to use
        - type: m5.xlarge            # required
           weight: 4                 # default to 1
        - type: m5.2xlarge
           weight: 8

    status:

      < .. status .. >

      activeLaunchTemplateName: some-template
```


### Use case examples:

A simple instancegroup using a launch template without mixed instance policy
```yaml
eks:
  type: LaunchTemplate
  minSize: 3
  maxSize: 6
    configuration:
      instanceType: m5.xlarge
```

An instancegroup using launch templates and generation flexible (auto derive) mixed instance policy without spot
```yaml
eks:
  type: LaunchTemplate
  minSize: 3
  maxSize: 6
    configuration:
      instanceType: m5.xlarge
      mixedInstancesPolicy:
        instancePool: GenerationFlexible
```

An instancegroup using launch templates and generation flexible (custom) mixed instance policy without spot
```yaml
eks:
  type: LaunchTemplate
  minSize: 3
  maxSize: 6
    configuration:
      instanceType: m5.xlarge
      mixedInstancesPolicy:
        instanceTypes:
        - type: m5d.xlarge
           weight: 1
        - type: m5a.xlarge
           weight: 1
```

An instancegroup using launch templates and generation flexible (auto derive) mixed instance policy with spot
```yaml
eks:
  type: LaunchTemplate
  minSize: 6
  maxSize: 9
    configuration:
      instanceType: m5.xlarge
      mixedInstancesPolicy:
        spotPools: 2
        baseCapacity: 3
        spotRatio: 50%
        instancePool: GenerationFlexible
```
The above will chose generation-flexible instance pools, and select two pools with the lowest price for spot, there will always be atleast 3 on-demand nodes present, and 50% of the rest (3-6 nodes) will be spot selected from 2 instance pools.

**Comment by shaoxt** [comment]
The syntax looks good to me.
These two templates will be highest priority to support.
```
eks:
  type: LaunchTemplate
  minSize: 3
  maxSize: 6
    configuration:
      instanceType: m5.xlarge
```

```
eks:
  type: LaunchTemplate
  minSize: 3
  maxSize: 6
    configuration:
      instanceType: m5.xlarge
      mixedInstancesPolicy:
        instanceTypes:
        - type: m5d.xlarge
        - type: m5a.xlarge
```
