### ISSUE TITLE
Instance-manager does not support KUBECONFIG as a path

### ISSUE THREAD

**Issue by preflightsiren** [keikoproj/instance-manager#181]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug Report

**What happened**: Running `go run ./main.go` with `KUBECONFIG=/Users/scole/.kube/config:/Users/scole/.kube/config-apptio-clusters:/Users/scole/.kube/config-eks` causes the startup to fail.

```
2020-10-29T10:19:12.506+1100	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2020-10-29T10:19:12.506+1100	ERROR	setup	unable to create kubernetes client	{"error": "stat /Users/scole/.kube/config:/Users/scole/.kube/config-apptio-clusters:/Users/scole/.kube/config-eks: no such file or directory"}
github.com/go-logr/zapr.(*zapLogger).Error
	/Users/scole/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
main.main
	/Users/scole/go/src/github.com/keikoproj/instance-manager/main.go:105
runtime.main
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/proc.go:204
exit status 1
```

**What you expected to happen**: that instance-manager starts and merges the config from every file in the `KUBECONFIG` path, using the current-context to configure which server to connect to.

**How to reproduce it (as minimally and precisely as possible)**:

`KUBECONFIG=$HOME/.kube/config:$HOME/kube/config go run ./main.go`

**Anything else we need to know?**: This might be an issue with the controller-runtime.

**Environment**:

- Kubernetes version:

```bash
kubectl version -o yaml
```

```
clientVersion:
  buildDate: "2020-09-16T21:51:49Z"
  compiler: gc
  gitCommit: f5743093fd1c663cb0cbc89748f730662345d44d
  gitTreeState: clean
  gitVersion: v1.19.2
  goVersion: go1.15.2
  major: "1"
  minor: "19"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-07-17T18:48:53Z"
  compiler: gc
  gitCommit: 2ba888155c7f8093a1bc06e3336333fbdb27b3da
  gitTreeState: clean
  gitVersion: v1.16.13-eks-2ba888
  goVersion: go1.13.9
  major: "1"
  minor: 16+
  platform: linux/amd64
```
