### ISSUE TITLE
EKS provisioner should support --use-max-pods field in spec

### ISSUE THREAD

**Issue by backjo** [keikoproj/instance-manager#184]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request
**What happened**:
If using custom networking on EKS, the number of max pods per node is reduced (see https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html). 

Instance Manager should allow setting --use-max-pods to false, so that nodes using custom networking can correctly set the maximum number of pods in bootstrap args. (Today, bootstrap args goes directly into --kubelet-extra-args)

**Comment by eytan-avisror** [comment]
Should we support this through annotations? e.g. `instancemgr.keikoproj.io/kubelet-arguments/use-max-pods: "false"`

I think changing the `bootstrapArgs` field to take kubelet arguments vs. --kubelet-extra-args is a bigger deal since it will break backwards compatiblity.

There are potentially other kubelet arguments we would like to allow control over.
WDYT

**Comment by backjo** [comment]
@eytan-avisror totally think we should not break backwards compatibility, and 'bootstrapArguments' should still continue to be what we pass into --kubelet-extra-args

I think one thing we should take into account is how these settings might map to BottleRocket AMIs - given that a lot of these properties overlap, but they are injected via TOML-formatted data in user data. 

I wonder if it makes sense to maintain bootstrapArguments as an escape hatch for new/unsupported arguments, but add some sort of structure for EKS-specific settings that might need special mapping or handling, similar to how node labels and taints are specified as part of the spec today. 
i.e. something like 
```yaml
configuration:
  bootstrapArgs: "--foo=bar"
  bootstrapData:
    maxPods: 20
    kubeletExtraArgs:
      evictionHard: "memory.available<300Mi"
```

This would map to the following bootstrap script for AL2 AMIs
```bash
bootstrap.sh --use-max-pods 'false' --kubelet-extra-args '--max-pods "20" --eviction-hard "memory.available<300mi" --foo="bar"'
```
But end up looking like this for BottleRocket AMIs
```toml
[settings.kubernetes]
max-pods = 20
```

Given that fields like max-pods are part of the core EKS bootstrap script or properties file, I think it makes more sense that they live as part of spec rather than as an annotation, but that's not a strong opinion.

**Comment by eytan-avisror** [comment]
So there are two types of flags here:
- Ones that go directly to the bootstrap.sh script such as `--use-max-pods`
- Ones that go to kubelet via `--kubelet-extra-args`

I feel that we can add structure around the bootstrap.sh scripts, but adding this structure around the kubelet arguments might be very difficult to manage - there are a LOT of flags, and they keep changing - adding structure will mean we have to keep track of these, while having an open string allows this to be untracked.

The bootstrap.sh script options are not that many and don't change very often, and since they are more concrete with EKS I would agree it makes sense to add structure around those.

We could add a new field like you suggested in order to avoid breaking backwards compat. e.g.

```yaml
configuration:
  bootstrapArguments: "--foo=bar"
  bootstrapOptions:
    useMaxPods: false
    dockerConfigJson: | 
       {
 	"bridge": "none",
 	"log-driver": "json-file",
 	"log-opts": {
 		"max-file": "5",
 		"max-size": "50"
       }
     }
    < other bootstrap.sh options excluding kubelet-extra-args >
```

And then this would be constructed in the userdata so that `bootstrapArguments` maps to `--kubelet-extra-args` and `bootstrapOptions` maps to direct flags passed to bootstrap.sh.

In v1alpha2 we can then rename `bootstrapArguments` into `kubeletArguments` which would be a more accurate name.

Regarding the bottle rocket AMI - can you explain who creates this TOML file? I don't see support for this within the bootstrap.sh script, is this AMI bootstrapped differently?

**Comment by eytan-avisror** [comment]
Another option that might be easier is to not exclude kubelet-extra-args and merge the two fields for now (similar to what you suggested), and deprecate `bootstrapArguments` field in v1alpha2, so that you can submit something like:

```yaml
configuration:
  bootstrapArguments: "--foo=bar"
  bootstrapOptions:
    kubeletArguments: "--max-pods 20 --eviction-hard memory.available<300mi"
    useMaxPods: false
    dockerConfigJson: | 
       {
 	"bridge": "none",
 	"log-driver": "json-file",
 	"log-opts": {
 		"max-file": "5",
 		"max-size": "50"
       }
     }
    < other bootstrap.sh options>
```

Would result in:
```
bootstrap.sh <clustername> --use-max-pods 'false' --docker-config-json "<JSON payload>" --kubelet-extra-args '--max-pods "20" --eviction-hard "memory.available<300mi" --foo="bar" '
```
