### ISSUE TITLE
Support EC2 Instance Metadata Options

### ISSUE THREAD

**Issue by backjo** [keikoproj/instance-manager#291]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

A common threat vector on AWS is through SSRF on the IMDS endpoint. Security-inclined users may wish to require IMDSv2 or restrict the hop limit for the metadata interface. We should allow users to control these settings.

**Comment by eytan-avisror** [comment]
Do you mean from the perspective of the API calls the controller makes? e.g. it should be configurable to only allow IMDSv2?
Can you elaborate on this further?

**Comment by backjo** [comment]
We can configure the IG LaunchTemplate or LaunchConfiguration to launch instances with MetadataOptions - which look something like this -> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-metadataoptions.html.

**Comment by eytan-avisror** [comment]
Got it, so we want an API to expose `InstanceMetadataOptions` for launch config:
https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#InstanceMetadataOptions

And `LaunchTemplateInstanceMetadataOptionsRequest` for launch template:
https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#LaunchTemplateInstanceMetadataOptionsRequest

Any thoughts on API?
```yaml
spec:
  eks:
    configuration:
      metadataOptions:
        httpEndpoint: <string "enabled" or "disabled">
        httpTokens: <string "optional" or "required"> 
        hopLimit: <int 1-64 default 1>
```

Can we simplify this further by adding an annotation instead e.g. `instancemgr.keikoproj.io/imdsv2-strict: "true"` would configure the launch config/template with:
```
        httpEndpoint: "enabled"
        httpTokens: "required"
        hopLimit: 1
```

Do we want to make it more flexible? or would annotation be OK? WDYT
