### ISSUE TITLE
IGs in special AWS partitions always fails ARN format validation in instance_types.go 

### ISSUE THREAD

**Issue by srosenberg-apptio** [keikoproj/instance-manager#373]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**What happened**:
Unable to add license specifications and placement configuration to instance_groups for GovCloud resources since ARN prefix validation is hard coded to expect AWS commercial ARN partition.

**What you expected to happen**:
I would expect the instanceGroups be able to successfully process and configure LaunchTemplates regardless of AWS partition.

**How to reproduce it (as minimally and precisely as possible)**:
Configure instanceGroup to have a valid GovCloud ARN in `LicenseSpecifications`, `NotificationArn` and/or `HostResourceGroupArn`. 

**Anything else we need to know?**:

Direct code snippets where the problem is and will occur with the use of `strings.HasPrefix(<arn>, awsprovider.ARNPrefix)` as the method to validate arn formats.

https://github.com/keikoproj/instance-manager/blob/ae893c45a9cdb3ca6bf557b9d73e0abdd782f67a/api/v1alpha1/instancegroup_types.go#L569

https://github.com/keikoproj/instance-manager/blob/ae893c45a9cdb3ca6bf557b9d73e0abdd782f67a/api/v1alpha1/instancegroup_types.go#L572

https://github.com/keikoproj/instance-manager/blob/ae893c45a9cdb3ca6bf557b9d73e0abdd782f67a/api/v1alpha1/instancegroup_types.go#L622

https://github.com/keikoproj/instance-manager/blob/ae893c45a9cdb3ca6bf557b9d73e0abdd782f67a/api/v1alpha1/instancegroup_types.go#L646

https://github.com/keikoproj/instance-manager/blob/ae893c45a9cdb3ca6bf557b9d73e0abdd782f67a/controllers/providers/aws/aws.go#L71

The AWS SDK has the `IsArn` function found in their ARN module (github.com/aws/aws-sdk-go/aws/arn) that should be able to provided the needed facility to validate ARNs.

**Environment**:

- Kubernetes version:
v1.21

**Other debugging information (if applicable)**:

- InstanceGroup status:
```
status:
  configMD5: 23dce88e71ab7fcc8ef222ff636f77d0
  currentState: Error
  lifecycle: normal
  nodesInstanceRoleArn: arn:aws-us-gov:iam::012345678901:role/eks-fake-role-us-gov-west-1
  provisioner: eks
  strategy: crd
```

Relevent manifest configuration details:
```
# ... snip

Spec:
  Eks:
    Configuration:
# ... snip
      licenseSpecifications:
      - arn:aws-us-gov:license-manager:us-gov-west-1:012345678901:license-configuration:lic-0a88baf9a84f39df630da6e67000f88f
      metricsCollection:
      - all
      placement:
        hostResourceGroupArn: arn:aws-us-gov:resource-groups:us-gov-west-1:012345678901:group/ig-1
        tenancy: host
# ... snip
```

- controller logs:

```
controller.instancegroup Reconciler error {reconciler group: instancemgr.keikoproj.io, reconciler kind: InstanceGroup, name: ig-us-gov-west-1a, namespace: instance-manager, error: provisioner eks reconcile failed: validation failed, 'LicenseSpecifications[0]' must be a valid IAM role ARN, errorVerbose: validation failed, 'LicenseSpecifications[0]' must be a valid IAM role ARN
github.com/keikoproj/instance-manager/api/v1alpha1.(*EKSConfiguration).Validate
	/workspace/api/v1alpha1/instancegroup_types.go:623
github.com/keikoproj/instance-manager/api/v1alpha1.(*InstanceGroup).Validate
	/workspace/api/v1alpha1/instancegroup_types.go:741
github.com/keikoproj/instance-manager/controllers.(*InstanceGroupReconciler).Reconcile
	/workspace/controllers/instancegroup_controller.go:197
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:214
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1581
provisioner eks reconcile failed
github.com/keikoproj/instance-manager/controllers.(*InstanceGroupReconciler).Reconcile
	/workspace/controllers/instancegroup_controller.go:201
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:214
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1581}
```
