### ISSUE TITLE
not honoring gp3 volume iops and throughput values

### ISSUE THREAD

**Issue by vgunapati** [keikoproj/instance-manager#379]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:

### Describe the bug

As part of gp3 testing, added rootVolume fields for gp3 volumeType and configuration. https://github.intuit.com/gitops/iksm-cluster-gitops/pull/4314/files

Instance manager created volume with `Type:gp3` but not  honoring `iops` and `throughput` values.

![image](https://user-images.githubusercontent.com/1102401/229255778-952dadfc-9f69-4db9-8cc3-9093525fab71.png)

IntanceGroup Spec:
```
apiVersion: instancemgr.keikoproj.io/v1alpha1
kind: InstanceGroup
metadata:
  annotations:
    instancemgr.keikoproj.io/irsa-enabled: "true"
  creationTimestamp: "2020-12-01T12:46:05Z"
  finalizers:
  - finalizer.instancegroups.keikoproj.io
  generation: 38
  name: nodes
  namespace: instance-manager
spec:
  eks:
    configuration:
      instanceType: m5.xlarge
      tags:
      - key: k8s.io/cluster-autoscaler/node-template/resources/ephemeral-storage
        value: 435Gi
      volumes:
      - iops: 3500
        name: /dev/xvda
        size: 512
        throughput: 250
        type: gp3
    maxSize: 50
    minSize: 3
  provisioner: eks
```

### To Reproduce

1. TBD

### Root Cause

Describe how this bug was introduced and how similar bugs could be prevented in the future.

### Additional context

> **NOTE:** Please be sure to add the appropriate `area/*` and priority labels. Please also set the Projects to include `IKS Team FYxx-Qx` to indicate when this work should be done.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kubernetes version:

```bash
kubectl version -o yaml
```

**Other debugging information (if applicable)**:

- InstanceGroup status:

```bash
kubectl describe instancegroup <ig-name>
```

- controller logs:

```bash
kubectl logs <instance-manager pod>
```
