### ISSUE TITLE
RollingUpdate configuration gets set regardless of chose strategy

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/instance-manager#51]
Since we added #39, it now sets the `rollingUpdate` configuration even if you are using CRD strategy.

For example, if you describe the YAML of an IG that has been using CRD Strategy you might see:
```yaml
strategy: 
  type: crd
  crd: 
    crdName: rollingupgrades
    spec: |
        apiVersion: upgrademgr.orkaproj.io/v1alpha1
        kind: RollingUpgrade
        metadata:
          name: rollup-nodes
          namespace: instance-manager
        spec:
          postDrainDelaySeconds: 30
          nodeIntervalSeconds: 180
          region: {{ .ControllerRegion }}
          asgName: {{ .InstanceGroup.Status.ActiveScalingGroupName }}
    statusJSONPath: .status.currentStatus
    statusSuccessString: completed
  rollingUpdate: 
    maxBatchSize: 1
    minInstancesInService: 1
    minSuccessfulInstancesPercent: 100
    pauseTime: PT5M
```

Setting these defaults when user is using crd strategy is just confusing, rollingUpdate should be set to `{}` or omitted and populated only if `type: rollingUpdate`
