### ISSUE TITLE
Not able to create instance group using latest release (0.5.0) and the provided sample yaml spec

### ISSUE THREAD

**Issue by darrendao** [keikoproj/instance-manager#81]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**What happened**:
Not able to create instance group using latest release (0.5.0) and the provided sample yaml spec

**What you expected to happen**:
We should be able to create instance group using the sample yaml

**How to reproduce it (as minimally and precisely as possible)**:
Using latest release (0.5.0)
Create an instance group using the instruction in the doc: https://github.com/keikoproj/instance-manager/tree/master/docs#create-an-intancegroup-object
Look at controller log and you will see the error

**Other debugging information (if applicable)**:

- controller logs:
```
time="2020-03-24T22:07:53Z" level=error msg="failed to load cloudformation configuration: template: InstanceGroup:204:38: executing \"InstanceGroup\" at <.Spec.AwsUpgradeStrategy.RollingUpgradeType.MinInstancesInService>: can't evaluate field MinInstancesInService in type *v1alpha1.RollingUpgradeStrategy"
time="2020-03-24T22:07:53Z" level=error msg="template: InstanceGroup:204:38: executing \"InstanceGroup\" at <.Spec.AwsUpgradeStrategy.RollingUpgradeType.MinInstancesInService>: can't evaluate field MinInstancesInService in type *v1alpha1.RollingUpgradeStrategy"
time="2020-03-24T22:07:53Z" level=info msg="reconcile completed with requeue"
```
I believe this is caused by this change: https://github.com/keikoproj/instance-manager/commit/5a6f76d72c345e4bfd2d71156bd7e27dfb132af5#diff-fe058806af3b4349a786152df5cbc36cR85. Since `RollingUpgradeType` is changed to a pointer, it will now be nil when we don't specify the `rollingUpdate` block in the yaml spec (rather than resolving to an empty struct with default values). I verified this by trying to create an instance group using a yaml spec that contains the `rollingUpdate` block and that worked. Example:
```
cat <<EOF | kubectl create -f -
apiVersion: instancemgr.keikoproj.io/v1alpha1
kind: InstanceGroup
metadata:
  name: hello-world
  namespace: instance-manager
spec:
  provisioner: eks-cf
  strategy:
    type: rollingUpdate
    rollingUpdate:
      maxBatchSize: 0
      minInstancesInService: 0
      minSuccessfulInstancesPercent: 0
  eks-cf:
    maxSize: 6
    minSize: 3
    configuration:
      clusterName: $EKS_CLUSTER_NAME
      vpcId: $VPC_ID
      subnets: $NODE_GROUP_SUBNET_LIST
      keyPairName: $KEYPAIR_NAME
      image: $NODE_AMI_ID
      instanceType: m5.large
      volSize: 20
      securityGroups:
      - $NODE_SECURITY_GROUP
      tags:
        - key: k8s.io/cluster-autoscaler/enabled
          value: "true"
        - key: hello
          value: world
EOF
```

So it looks like `rollingUpdate` is now a mandary field. Is that what we really want? Users shouldn't have to specify it if they're ok with the default values.

**Comment by eytan-avisror** [comment]
@darrendao 
I think you need to update your CRD since we changed some types to pointers - there were CRD changes with this release.

Our nightly functional tests are passing here:
https://travis-ci.org/github/keikoproj/instance-manager/builds/667478575

Some of these types were made into pointers so that we can take advantage of `omitempty`
Otherwise for example you can end up with a spec that looks like this:
```
apiVersion: instancemgr.keikoproj.io/v1alpha1
kind: InstanceGroup
metadata:
  annotations:
  name: hello-managed
  namespace: instance-manager
spec:
  provisioner: eks-managed
  strategy:
    type: managed
  eks-cf: {}   <-- not omitted
  eks-managed:
    configuration:
      < .. >
    maxSize: 6
    minSize: 3
```

**Comment by darrendao** [comment]
@eytan-avisror I got the error on a fresh K8S setup using the latest CRD provided in https://github.com/keikoproj/instance-manager/blob/master/docs/04_instance-manager.yaml (per instructions in the docs).

**Comment by eytan-avisror** [comment]
I see, our tests are running with this struct populated:
```
rollingUpdate:
      maxBatchSize: 1
      minInstancesInService: 1
      minSuccessfulInstancesPercent: 100
      pauseTime: PT2M
```

so it's possible that this is why we're not seeing it.
I guess what we should do here is set default values in the controller if this struct is unset - this is a required struct and we should probably also add it to the examples as it defines the configuration of the rollingUpdate, we should not be omitting it.
